//package com.Utils;
//
//import com.Entity.Attack;
//import com.Entity.Type;
//
//import java.util.ArrayList;
//
///**
// * Created by Mathieu on 18/06/2016.
// */
//public class AttackBuilder {
//
//    public static ArrayList<Attack> getAttackList()
//    {
//        ArrayList<Attack> attacks = new ArrayList<Attack>();
//
//        attacks.add(new Attack(Type.Ground,"Abîme",true,200,30));
//        attacks.add(new Attack(Type.Poison,"Acidarmure",true,0,0));
//        attacks.add(new Attack(Type.Poison,"Acide",true,40,100));
//        attacks.add(new Attack(Type.Normal,"Adaptation",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Affûtage",true,0,0));
//        attacks.add(new Attack(Type.Psychic,"Amnésie",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Armure",true,0,0));
//        attacks.add(new Attack(Type.Fight,"Balayage",true,50,100));
//        attacks.add(new Attack(Type.Flying,"Bec Vrille",true,80,100));
//        attacks.add(new Attack(Type.Normal,"Bélier",true,90,85));
//        attacks.add(new Attack(Type.Normal,"Berceuse",true,0,55));
//        attacks.add(new Attack(Type.Ice,"Blizzard",true,120,70));
//        attacks.add(new Attack(Type.Normal,"Bomb\"Œuf",true,100,75));
//        attacks.add(new Attack(Type.Psychic,"Bouclier",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Boul\"Armure",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Brouillard",true,0,100));
//        attacks.add(new Attack(Type.Ice,"Brume",true,0,0));
//        attacks.add(new Attack(Type.Ice,"Buée Noire",true,0,0));
//        attacks.add(new Attack(Type.Water,"Bulles d\"O",true,65,100));
//        attacks.add(new Attack(Type.Electric,"Cage-Éclair",true,0,100));
//        attacks.add(new Attack(Type.Water,"Cascade",true,80,100));
//        attacks.add(new Attack(Type.Normal,"Charge",true,50,100));
//        attacks.add(new Attack(Type.Psychic,"Choc Mental",true,50,100));
//        attacks.add(new Attack(Type.Water,"Claquoir",true,35,85));
//        attacks.add(new Attack(Type.Normal,"Clonage",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Combo-Griffe",true,18,80));
//        attacks.add(new Attack(Type.Normal,"Constriction",true,10,100));
//        attacks.add(new Attack(Type.Normal,"Copie",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Coup d\"Boule",true,70,100));
//        attacks.add(new Attack(Type.Normal,"Coupe",true,50,95));
//        attacks.add(new Attack(Type.Normal,"Coupe-Vent",true,80,100));
//        attacks.add(new Attack(Type.Normal,"Croc de Mort",true,80,90));
//        attacks.add(new Attack(Type.Normal,"Croc Fatal",true,0,90));
//        attacks.add(new Attack(Type.Normal,"Croissance",true,0,0));
//        attacks.add(new Attack(Type.Flying,"Cru-Aile",true,60,100));
//        attacks.add(new Attack(Type.Normal,"Cyclone",true,0,100));
//        attacks.add(new Attack(Type.Rock,"Éboulement",true,75,90));
//        attacks.add(new Attack(Type.Normal,"E-Coque",true,0,100));
//        attacks.add(new Attack(Type.Electric,"Éclair",true,40,100));
//        attacks.add(new Attack(Type.Normal,"Écrasement",true,65,100));
//        attacks.add(new Attack(Type.Normal,"Écras\"Face",true,40,100));
//        attacks.add(new Attack(Type.Water,"Écume",true,20,100));
//        attacks.add(new Attack(Type.Normal,"Empal\"Korne",true,200,0));
//        attacks.add(new Attack(Type.Normal,"Entrave",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Explosion",true,250,100));
//        attacks.add(new Attack(Type.Normal,"Poing-Karaté",true,50,100));
//        attacks.add(new Attack(Type.Normal,"Torgnoles",true,15,85));
//        attacks.add(new Attack(Type.Normal,"Poing Comète",true,18,85));
//        attacks.add(new Attack(Type.Normal,"Ultimapoing",true,80,85));
//        attacks.add(new Attack(Type.Normal,"Jackpot",true,40,100));
//        attacks.add(new Attack(Type.Fire,"Poing-De-Feu",true,75,100));
//        attacks.add(new Attack(Type.Electric,"Poing-Éclair",true,75,100));
//        attacks.add(new Attack(Type.Normal,"Griffe",true,40,100));
//        attacks.add(new Attack(Type.Normal,"Force Poigne",true,55,100));
//        attacks.add(new Attack(Type.Normal,"Guillotine",true,200,0));
//        attacks.add(new Attack(Type.Normal,"Danse-Lames",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Tornade",true,40,100));
//        attacks.add(new Attack(Type.Flying,"Vol",true,90,95));
//        attacks.add(new Attack(Type.Normal,"Étreinte",true,15,85));
//        attacks.add(new Attack(Type.Normal,"Souplesse",true,80,75));
//        attacks.add(new Attack(Type.Grass,"Fouet Lianes",true,35,100));
//        attacks.add(new Attack(Type.Fight,"Double-Pied",true,60 ,100));
//        attacks.add(new Attack(Type.Normal,"Ultimawashi",true,120,75));
//        attacks.add(new Attack(Type.Fight,"Pied Sauté",true,100,95));
//        attacks.add(new Attack(Type.Fight,"Mawashi Geri",true,60,85));
//        attacks.add(new Attack(Type.Normal,"Jet de Sable",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Koud\"Korne",true,65,100));
//        attacks.add(new Attack(Type.Normal,"Furie",true,15,85));
//        attacks.add(new Attack(Type.Normal,"Plaquage",true,85,100));
//        attacks.add(new Attack(Type.Normal,"Ligotage",true,15,90));
//        attacks.add(new Attack(Type.Normal,"Mania",true,120,100));
//        attacks.add(new Attack(Type.Normal,"Damoclès",true,120,100));
//        attacks.add(new Attack(Type.Normal,"Mimi-Queue",true,0,100));
//        attacks.add(new Attack(Type.Poison,"Dard-Venin",true,15,100));
//        attacks.add(new Attack(Type.Bug,"Double-Dard",true,25,100));
//        attacks.add(new Attack(Type.Bug,"Dard-Nuée",true,14,85));
//        attacks.add(new Attack(Type.Normal,"Groz\"Yeux",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Morsure",true,60,100));
//        attacks.add(new Attack(Type.Normal,"Rugissement",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Hurlement",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Ultrason",true,0,55));
//        attacks.add(new Attack(Type.Normal,"Sonicboom",true,0,90));
//        attacks.add(new Attack(Type.Fire,"Flammèche",true,40,100));
//        attacks.add(new Attack(Type.Fire,"Lance-Flamme",true,95,100));
//        attacks.add(new Attack(Type.Water,"Pistolet à O",true,40,100));
//        attacks.add(new Attack(Type.Water,"Hydrocanon",true,120,80));
//        attacks.add(new Attack(Type.Water,"Surf",true,95,100));
//        attacks.add(new Attack(Type.Normal,"Laser",true,95,100));
//        attacks.add(new Attack(Type.Normal,"Rafale",true,65,100));
//        attacks.add(new Attack(Type.Ice,"Onde Boréale",true,65,100));
//        attacks.add(new Attack(Type.Ice,"Poing-Glace",true,75,100));
//        attacks.add(new Attack(Type.Ice,"Laser-Glace",true,95,100));
//        attacks.add(new Attack(Type.Normal,"Ultralaser",true,150,90));
//        attacks.add(new Attack(Type.Flying,"Picpic",true,35,100));
//        attacks.add(new Attack(Type.Fight,"Sacrifice",true,80,80));
//        attacks.add(new Attack(Type.Fight,"Riposte",true,0,100));
//        attacks.add(new Attack(Type.Fight,"Frappe Atlas",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Force",true,80,100));
//        attacks.add(new Attack(Type.Grass,"Vol-Vie",true,20,100));
//        attacks.add(new Attack(Type.Grass,"Méga-Sangsue",true,40,100));
//        attacks.add(new Attack(Type.Grass,"Vampigraine",true,0,90));
//        attacks.add(new Attack(Type.Grass,"Tranch\"Herbe",true,55,95));
//        attacks.add(new Attack(Type.Grass,"Lance-soleil",true,120,100));
//        attacks.add(new Attack(Type.Poison,"Poudre Toxik",true,0,75));
//        attacks.add(new Attack(Type.Grass,"Para-Spore",true,0,75));
//        attacks.add(new Attack(Type.Grass,"Poudre Dodo",true,0,75));
//        attacks.add(new Attack(Type.Grass,"Danse-Fleur",true,120,100));
//        attacks.add(new Attack(Type.Bug,"Sécrétion",true,0,95));
//        attacks.add(new Attack(Type.Dragon,"Draco-Rage",true,0,100));
//        attacks.add(new Attack(Type.Fire,"Danseflamme",true,35,85));
//        attacks.add(new Attack(Type.Electric,"Tonnerre",true,95,100));
//        attacks.add(new Attack(Type.Electric,"Fatal-Foudre",true,120,70));
//        attacks.add(new Attack(Type.Rock,"Jet-Pierres",true,50,90));
//        attacks.add(new Attack(Type.Ground,"Séisme",true,100,100));
//        attacks.add(new Attack(Type.Ground,"Tunnel",true,80,100));
//        attacks.add(new Attack(Type.Poison,"Toxik",true,0,90));
//        attacks.add(new Attack(Type.Normal,"11ko",true,90,100));
//        attacks.add(new Attack(Type.Psychic,"Hypnose",true,0,60));
//        attacks.add(new Attack(Type.Psychic,"Psyko",true,90,100));
//        attacks.add(new Attack(Type.Psychic,"Yoga",true,0,0));
//        attacks.add(new Attack(Type.Psychic,"Hâte",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Vive-Attaque",true,40,100));
//        attacks.add(new Attack(Type.Normal,"Frénésie",true,20,100));
//        attacks.add(new Attack(Type.Psychic,"Téléport",true,0,0));
//        attacks.add(new Attack(Type.Ghost,"Ténèbres",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Grincement",true,0,85));
//        attacks.add(new Attack(Type.Normal,"Reflet",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Soin",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Lilliput",true,0,0));
//        attacks.add(new Attack(Type.Ghost,"Onde Folie",true,0,100));
//        attacks.add(new Attack(Type.Water,"Repli",true,0,0));
//        attacks.add(new Attack(Type.Psychic,"Mur Lumière",true,0,0));
//        attacks.add(new Attack(Type.Psychic,"Protection",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Puissance",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Patience",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Métronome",true,0,0));
//        attacks.add(new Attack(Type.Flying,"Mimique",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Destruction",true,200,100));
//        attacks.add(new Attack(Type.Ghost,"Léchouille",true,20,100));
//        attacks.add(new Attack(Type.Poison,"Purédpois",true,20,70));
//        attacks.add(new Attack(Type.Poison,"Détritus",true,65,100));
//        attacks.add(new Attack(Type.Ground,"Massd\"Os",true,65,85));
//        attacks.add(new Attack(Type.Fire,"Déflagration",true,120,85));
//        attacks.add(new Attack(Type.Normal,"Météores",true,60,0));
//        attacks.add(new Attack(Type.Normal,"Coud\"Krâne",true,100,100));
//        attacks.add(new Attack(Type.Normal,"Picanon",true,20,100));
//        attacks.add(new Attack(Type.Psychic,"Télékinésie",true,0,80));
//        attacks.add(new Attack(Type.Fight,"Pied Voltige",true,130,90));
//        attacks.add(new Attack(Type.Normal,"Intimidation",true,0,90));
//        attacks.add(new Attack(Type.Psychic,"Dévorêve",true,100,100));
//        attacks.add(new Attack(Type.Poison,"Gaz Toxik",true,0,80));
//        attacks.add(new Attack(Type.Normal,"Pilonnage",true,15,85));
//        attacks.add(new Attack(Type.Normal,"Vampirisme",true,20,100));
//        attacks.add(new Attack(Type.Normal,"Grobisou",true,0,75));
//        attacks.add(new Attack(Type.Flying,"Piqué",true,140,90));
//        attacks.add(new Attack(Type.Normal,"Morphing",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Uppercut",true,70,100));
//        attacks.add(new Attack(Type.Grass,"Spore",true,0,100));
//        attacks.add(new Attack(Type.Normal,"Flash",true,0,100));
//        attacks.add(new Attack(Type.Psychic,"Vague Psy",true,0,80));
//        attacks.add(new Attack(Type.Normal,"Trempette",true,0,0));
//        attacks.add(new Attack(Type.Water,"Pince-Masse",true,90,90));
//        attacks.add(new Attack(Type.Ground,"Osmerang",true,50 ,90));
//        attacks.add(new Attack(Type.Psychic,"Repos",true,0,0));
//        attacks.add(new Attack(Type.Normal,"Triplattaque",true,80,100));
//        attacks.add(new Attack(Type.Normal,"Tranche",true,70,100));
//        attacks.add(new Attack(Type.Normal,"Lutte",true,50,100));
//
//        return attacks;
//    }
//}
